In [13]:
import pandas as pd
from rdkit.Chem import MolFromSmiles, Descriptors

In [14]:
df = pd.read_csv("ADME_public_set_3521.csv")
df

,Internal ID,Vendor ID,SMILES,CollectionName,LOG HLM_CLint (mL/min/kg),LOG MDR1-MDCK ER (B-A/A-B),LOG SOLUBILITY PH 6.8 (ug/mL),LOG PLASMA PROTEIN BINDING (HUMAN) (% unbound),LOG PLASMA PROTEIN BINDING (RAT) (% unbound),LOG RLM_CLint (mL/min/kg)
0,Mol1,317714313,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,emolecules,0.675687,1.493167,0.089905,0.991226,0.518514,1.392169
1,Mol2,324056965,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,emolecules,0.675687,1.040780,0.550228,0.099681,0.268344,1.027920
2,Mol3,304005766,CN(c1ncc(F)cn1)[C@H]1CCCNC1,emolecules,0.675687,-0.358806,NaN,2.000000,2.000000,1.027920
3,Mol4,194963090,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,emolecules,0.675687,1.026662,1.657056,-1.158015,-1.403403,1.027920
4,Mol5,324059015,CC(C)(O)CCn1cc2cc(NC(=O)c3cccc(C(F)(F)F)n3)c(C...,emolecules,0.996380,1.010597,NaN,1.015611,1.092264,1.629093
...,...,...,...,...,...,...,...,...,...,...
3516,Mol3517,43258693,O=C(c1ccc2c(c1)CCCC2)N1CCOCC1c1ccn[nH]1,emolecules,NaN,0.606813,NaN,NaN,NaN,NaN
3517,Mol3518,27448206,O=C(Nc1nc2ccccc2[nH]1)c1ccc(-n2cccc2)cc1,emolecules,NaN,-0.444495,NaN,NaN,NaN,NaN
3518,Mol3519,207150215,NC(=O)c1noc([C@@H](CCCC2CCCCC2)CC(=O)NO)n1,emolecules,0.863799,NaN,NaN,NaN,NaN,NaN
3519,Mol3520,25037224,CCCCCCCCc1ccc(CC[C@](N)(CO)COP(=O)(O)O)cc1,emolecules,0.881385,NaN,NaN,NaN,NaN,NaN
3520,Mol3521,53744885,Cc1cccc(/C=N/Nc2cc(N3CCOCC3)n3nc(-c4ccncc4)cc3...,emolecules,1.507059,NaN,NaN,NaN,NaN,NaN

In [15]:
def featurise(smiles: str) -> dict:
    mol = MolFromSmiles(smiles)
    return pd.Series(Descriptors.CalcMolDescriptors(mol))

In [16]:
sol_df = df[["SMILES", "LOG SOLUBILITY PH 6.8 (ug/mL)"]].dropna()
sol_df

,SMILES,LOG SOLUBILITY PH 6.8 (ug/mL)
0,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,0.089905
1,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,0.550228
3,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,1.657056
5,CC#CC(=O)N[C@H]1CCCN(c2c(F)cc(C(N)=O)c3[nH]c(C...,1.033424
8,C=CC(=O)N1CCC[C@@H](n2nc(-c3ccc(Oc4ccccc4)cc3)...,0.933990
...,...,...
3492,Cc1cc(C)cc(C(=O)NCCCNc2ncccn2)c1,1.720449
3493,CCc1noc(COc2c(C)ccnc2Cl)n1,1.366983
3494,CC(C)(C)Cc1nnc(-c2cnc3onc(C4CCCC4)c3c2)o1,0.600973
3495,Cc1nonc1C(=O)NCCc1c[nH]c2cccc(C3(O)CCOCC3)c12,1.786751
3496,CN1CC(=O)N(CCOc2ccccc2)C1=O,1.362671

In [17]:
sol_features = sol_df["SMILES"].apply(featurise)

Strip descriptors with any 0 values

In [18]:
#sol_features = sol_features.loc[:, (sol_features != 0).all(axis=0)]
sol_features

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,13.200851,13.200851,0.165008,-1.018011,0.424174,17.187500,434.435,415.283,434.161500,162.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,12.876020,12.876020,0.114613,-2.761275,0.572869,11.833333,418.444,394.252,418.181647,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,11.185594,11.185594,0.434476,-1.299581,0.655493,11.222222,382.847,363.695,382.108420,138.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,15.051509,15.051509,0.113230,-0.672570,0.723064,16.740741,370.428,347.244,370.180504,142.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,12.171747,12.171747,0.005660,-0.069880,0.466703,16.000000,440.507,416.315,440.196074,166.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,12.026045,12.026045,0.029851,-0.029851,0.798935,10.190476,284.363,264.203,284.163711,110.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
3493,5.925485,5.925485,0.193704,0.193704,0.783974,10.529412,253.689,241.593,253.061804,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3494,5.823318,5.823318,0.107271,0.107271,0.703941,16.291667,326.400,304.224,326.174276,126.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3495,12.148680,12.148680,0.200123,-0.887455,0.631431,16.518519,370.409,348.233,370.164105,142.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3496,11.533550,11.533550,0.156915,-0.257721,0.728987,15.588235,234.255,220.143,234.100442,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [19]:
sol_features.to_csv("adme_sol_training.txt", header=False, index=False, sep=" ")

In [20]:
sol_features.to_csv("adme_sol_feature_subset_training.txt", columns=['MolWt', 'FractionCSP3', 'NumHAcceptors', 'NumHDonors', 'NOCount', 'NHOHCount',
              'NumAliphaticRings', 'NumAliphaticHeterocycles', 'NumAromaticHeterocycles', 'NumAromaticRings', 
              'NumRotatableBonds', 'TPSA', 'qed', 'MolLogP'], header=False, index=False, sep=" ")

In [21]:
sol_df.to_csv("adme_sol_response.txt", columns=["LOG SOLUBILITY PH 6.8 (ug/mL)"], header=False, index=False)